video_root: ./video_data
ann_root: annotation/data/refined_msrvtt_ret

# set pretrained as a file path or an url
pretrained: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base.pth

# size of vit model; base or large
vit: base
image_size: 384
num_frm_test: 4
batch_size_train: 2
batch_size_test: 2
vit_grad_ckpt: true
vit_ckpt_layer: 4
init_lr: 1e-5

queue_size: 57600
alpha: 0.4
k_test: 12
negative_all_rank: true

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 1
