video_root: ./video_data
ann_root: annotation/data/refined_msrvtt_ret

# set pretrained as a file path or an url
pretrained: ./output/Retrieval_msrvtt_train/checkpoint_best.pth

# size of vit model; base or large
vit: base
batch_size: 8
k_test: 12
image_size: 384
num_frm_test: 8
